# baseURL = "https://if001.github.io/book_impressions/"
baseURL = "https://book.if-blog.site"
languageCode = "ja"
title = "読書録"
theme = "myharbor"

DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir= "docs"
ignoreFiles = ["/posts/*/\\.#*"]
hasCJKLanguage = true

   
[Author]
  name = "if_004"

[outputs]
  section = ["JSON", "HTML"]
 
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
    
[blackfriday]
   hrefTargetBlank = true

[[params.nav]]
  identifier = "home"
  name = "Home"
  icon = "fas fa-home fa-lg"
  url = "/"
  weight = 3
  
# [[params.nav]]
#   identifier = "about"
#   name = "About"
#   icon = "fas fa-user fa-lg"
#   url = "/pages/about"
#   weight = 3

[[params.nav]]
  identifier = "authors"
  name = "Authors"
  icon = "fas fa-user fa-lg"
  url = "authors"
  weight = 3
  
[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3
  
# [[params.nav]]
#   identifier = "search"
#   name = "Search"
#   icon = "fas fa-search fa-lg"
#   url = "search"
#   weight = 3
  
[[params.social]]
  name= "twitter"
  url="https://twitter.com/if_004"
  icon="fab fa-twitter"
  
[taxonomies]
  tag = "tags"
  author = "authors"
  